Name - Dhruvit Jain

Branch/Stream - B. Tech ExTC

Semester - 7

DENS Lab Number - 0

Date of performance - 04/12/2020

Date of submission - 04/12/2020

In [56]:
#1 first and last character
string1 = "Dhruvit Jain"
n1 = len (string1)
first = string1[0]
last = string1[-1]
final_string = last+string1[1:n1-1]+first
print (final_string)

nhruvit JaiD


In [57]:
#reverse a number 
n1 = 123456
l1=[]
while n1>0:
    a = n1%10
    l1.append(a)
    n1=n1//10
print (l1)

n2 = ''.join([str(elem) for elem in l1])
print (n2)
n2=int (n2)


[6, 5, 4, 3, 2, 1]
654321


In [58]:
#3.	To write a program to print 2nd maximum and 2nd minimum number in the list using list sort()

list1 = [22,440,55667,78,89,8900,5467,0,1,48]
list1.sort()
print (list1)

print ("2nd minimum:")
print (list1[1])
print ("2nd maximum:")
print (list1[-2])

[0, 1, 22, 48, 78, 89, 440, 5467, 8900, 55667]
2nd minimum:
1
2nd maximum:
8900


In [59]:
#4.	To write a program to print the numbers which are not multiple of 5 in the given list using list append()

list1 = [5,10,15,21,36,40,45,56,70,80,96,99]
list2=[]
for elem in list1:
    if elem % 5 !=0:
        list2.append (elem)
print (list2)

[21, 36, 56, 96, 99]


In [60]:
#5.	Numpy
import numpy as np

#a.	Creating 4X4 numpy array
a1 = np.zeros((4,4)).astype(int)
print (a1)
print ("")
#b.	Extract all the elements of 3rd row from a 4x4 array
print (a1[3,])
print ("")

#c.	Reshape the original 4X4 array to 2X8 array
a2 = a1.reshape(2,8)
print (a2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[0 0 0 0]

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [61]:
#6.	Write a function called add_int that will take two integers as input and return its sum as output
def add_int (a,b):
    return (a+b)

sum1 = add_int(5,9)
print (sum1)

14


In [64]:
#7.	To write a Python program to create a dictionary
dict1 = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5, 'f':6}
print (dict1)

a1= ['a','b','c','d','e','f']
b1= [1,2,3,4,5,6]

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


In [53]:
#8.	To write a Python program to print keys and values of the dictionary using dict.keys(), dict.items()
print (dict1.keys())
print (dict1.values())

dict_keys(['a', 'b', 'c', 'd', 'e', 'f'])
dict_values([1, 2, 3, 4, 5, 6])
